// Generated by gencpp from file moveit_tutorial/pick.msg
// DO NOT EDIT!


#ifndef MOVEIT_TUTORIAL_MESSAGE_PICK_H
#define MOVEIT_TUTORIAL_MESSAGE_PICK_H

#include <ros/service_traits.h>


#include <moveit_tutorial/pickRequest.h>
#include <moveit_tutorial/pickResponse.h>


namespace moveit_tutorial
{

struct pick
{

typedef pickRequest Request;
typedef pickResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pick
} // namespace moveit_tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::moveit_tutorial::pick > {
  static const char* value()
  {
    return "24f5679e0a52d4e75d20787acf70c895";
  }

  static const char* value(const ::moveit_tutorial::pick&) { return value(); }
};

template<>
struct DataType< ::moveit_tutorial::pick > {
  static const char* value()
  {
    return "moveit_tutorial/pick";
  }

  static const char* value(const ::moveit_tutorial::pick&) { return value(); }
};


// service_traits::MD5Sum< ::moveit_tutorial::pickRequest> should match
// service_traits::MD5Sum< ::moveit_tutorial::pick >
template<>
struct MD5Sum< ::moveit_tutorial::pickRequest>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorial::pick >::value();
  }
  static const char* value(const ::moveit_tutorial::pickRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorial::pickRequest> should match
// service_traits::DataType< ::moveit_tutorial::pick >
template<>
struct DataType< ::moveit_tutorial::pickRequest>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorial::pick >::value();
  }
  static const char* value(const ::moveit_tutorial::pickRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::moveit_tutorial::pickResponse> should match
// service_traits::MD5Sum< ::moveit_tutorial::pick >
template<>
struct MD5Sum< ::moveit_tutorial::pickResponse>
{
  static const char* value()
  {
    return MD5Sum< ::moveit_tutorial::pick >::value();
  }
  static const char* value(const ::moveit_tutorial::pickResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::moveit_tutorial::pickResponse> should match
// service_traits::DataType< ::moveit_tutorial::pick >
template<>
struct DataType< ::moveit_tutorial::pickResponse>
{
  static const char* value()
  {
    return DataType< ::moveit_tutorial::pick >::value();
  }
  static const char* value(const ::moveit_tutorial::pickResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVEIT_TUTORIAL_MESSAGE_PICK_H
