(cl:in-package cw1_team_10-srv)
(cl:export '(EXAMPLE_FLOAT-VAL
          EXAMPLE_FLOAT
          EXAMPLE_INT-VAL
          EXAMPLE_INT
          EXAMPLE_STRING-VAL
          EXAMPLE_STRING
          EXAMPLE_POSE-VAL
          EXAMPLE_POSE
          EXAMPLE_STD_VECTOR_OF_POSES-VAL
          EXAMPLE_STD_VECTOR_OF_POSES
          SUCCESS-VAL
          SUCCESS
          EXAMPLE_STD_VECTOR_OF_POINTS-VAL
          EXAMPLE_STD_VECTOR_OF_POINTS
))