// Generated by gencpp from file cw1_world_spawner/TaskSetup.msg
// DO NOT EDIT!


#ifndef CW1_WORLD_SPAWNER_MESSAGE_TASKSETUP_H
#define CW1_WORLD_SPAWNER_MESSAGE_TASKSETUP_H

#include <ros/service_traits.h>


#include <cw1_world_spawner/TaskSetupRequest.h>
#include <cw1_world_spawner/TaskSetupResponse.h>


namespace cw1_world_spawner
{

struct TaskSetup
{

typedef TaskSetupRequest Request;
typedef TaskSetupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskSetup
} // namespace cw1_world_spawner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw1_world_spawner::TaskSetup > {
  static const char* value()
  {
    return "713f50eb6979d6bda1389d9b25c308e0";
  }

  static const char* value(const ::cw1_world_spawner::TaskSetup&) { return value(); }
};

template<>
struct DataType< ::cw1_world_spawner::TaskSetup > {
  static const char* value()
  {
    return "cw1_world_spawner/TaskSetup";
  }

  static const char* value(const ::cw1_world_spawner::TaskSetup&) { return value(); }
};


// service_traits::MD5Sum< ::cw1_world_spawner::TaskSetupRequest> should match
// service_traits::MD5Sum< ::cw1_world_spawner::TaskSetup >
template<>
struct MD5Sum< ::cw1_world_spawner::TaskSetupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw1_world_spawner::TaskSetup >::value();
  }
  static const char* value(const ::cw1_world_spawner::TaskSetupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1_world_spawner::TaskSetupRequest> should match
// service_traits::DataType< ::cw1_world_spawner::TaskSetup >
template<>
struct DataType< ::cw1_world_spawner::TaskSetupRequest>
{
  static const char* value()
  {
    return DataType< ::cw1_world_spawner::TaskSetup >::value();
  }
  static const char* value(const ::cw1_world_spawner::TaskSetupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw1_world_spawner::TaskSetupResponse> should match
// service_traits::MD5Sum< ::cw1_world_spawner::TaskSetup >
template<>
struct MD5Sum< ::cw1_world_spawner::TaskSetupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw1_world_spawner::TaskSetup >::value();
  }
  static const char* value(const ::cw1_world_spawner::TaskSetupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1_world_spawner::TaskSetupResponse> should match
// service_traits::DataType< ::cw1_world_spawner::TaskSetup >
template<>
struct DataType< ::cw1_world_spawner::TaskSetupResponse>
{
  static const char* value()
  {
    return DataType< ::cw1_world_spawner::TaskSetup >::value();
  }
  static const char* value(const ::cw1_world_spawner::TaskSetupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW1_WORLD_SPAWNER_MESSAGE_TASKSETUP_H
