// Generated by gencpp from file cw1_world_spawner/Task2ServiceRequest.msg
// DO NOT EDIT!


#ifndef CW1_WORLD_SPAWNER_MESSAGE_TASK2SERVICEREQUEST_H
#define CW1_WORLD_SPAWNER_MESSAGE_TASK2SERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace cw1_world_spawner
{
template <class ContainerAllocator>
struct Task2ServiceRequest_
{
  typedef Task2ServiceRequest_<ContainerAllocator> Type;

  Task2ServiceRequest_()
    : basket_locs()  {
    }
  Task2ServiceRequest_(const ContainerAllocator& _alloc)
    : basket_locs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::PointStamped_<ContainerAllocator> >> _basket_locs_type;
  _basket_locs_type basket_locs;





  typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Task2ServiceRequest_

typedef ::cw1_world_spawner::Task2ServiceRequest_<std::allocator<void> > Task2ServiceRequest;

typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceRequest > Task2ServiceRequestPtr;
typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceRequest const> Task2ServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator1> & lhs, const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.basket_locs == rhs.basket_locs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator1> & lhs, const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cw1_world_spawner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e66144401ea119f3c53b4b38229a003";
  }

  static const char* value(const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e66144401ea119fULL;
  static const uint64_t static_value2 = 0x3c53b4b38229a003ULL;
};

template<class ContainerAllocator>
struct DataType< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cw1_world_spawner/Task2ServiceRequest";
  }

  static const char* value(const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PointStamped[] basket_locs\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PointStamped\n"
"# This represents a Point with reference coordinate frame and timestamp\n"
"Header header\n"
"Point point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.basket_locs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Task2ServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cw1_world_spawner::Task2ServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "basket_locs[]" << std::endl;
    for (size_t i = 0; i < v.basket_locs.size(); ++i)
    {
      s << indent << "  basket_locs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.basket_locs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CW1_WORLD_SPAWNER_MESSAGE_TASK2SERVICEREQUEST_H
