// Generated by gencpp from file cw1_world_spawner/Task2ServiceResponse.msg
// DO NOT EDIT!


#ifndef CW1_WORLD_SPAWNER_MESSAGE_TASK2SERVICERESPONSE_H
#define CW1_WORLD_SPAWNER_MESSAGE_TASK2SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cw1_world_spawner
{
template <class ContainerAllocator>
struct Task2ServiceResponse_
{
  typedef Task2ServiceResponse_<ContainerAllocator> Type;

  Task2ServiceResponse_()
    : basket_colours()  {
    }
  Task2ServiceResponse_(const ContainerAllocator& _alloc)
    : basket_colours(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _basket_colours_type;
  _basket_colours_type basket_colours;





  typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Task2ServiceResponse_

typedef ::cw1_world_spawner::Task2ServiceResponse_<std::allocator<void> > Task2ServiceResponse;

typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceResponse > Task2ServiceResponsePtr;
typedef boost::shared_ptr< ::cw1_world_spawner::Task2ServiceResponse const> Task2ServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator1> & lhs, const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.basket_colours == rhs.basket_colours;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator1> & lhs, const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cw1_world_spawner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59b344007468b6fcbc96439ba236c68a";
  }

  static const char* value(const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59b344007468b6fcULL;
  static const uint64_t static_value2 = 0xbc96439ba236c68aULL;
};

template<class ContainerAllocator>
struct DataType< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cw1_world_spawner/Task2ServiceResponse";
  }

  static const char* value(const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] basket_colours\n"
"\n"
"\n"
;
  }

  static const char* value(const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.basket_colours);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Task2ServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cw1_world_spawner::Task2ServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "basket_colours[]" << std::endl;
    for (size_t i = 0; i < v.basket_colours.size(); ++i)
    {
      s << indent << "  basket_colours[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.basket_colours[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CW1_WORLD_SPAWNER_MESSAGE_TASK2SERVICERESPONSE_H
