// Generated by gencpp from file cw1_world_spawner/TaskSetupResponse.msg
// DO NOT EDIT!


#ifndef CW1_WORLD_SPAWNER_MESSAGE_TASKSETUPRESPONSE_H
#define CW1_WORLD_SPAWNER_MESSAGE_TASKSETUPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cw1_world_spawner
{
template <class ContainerAllocator>
struct TaskSetupResponse_
{
  typedef TaskSetupResponse_<ContainerAllocator> Type;

  TaskSetupResponse_()
    {
    }
  TaskSetupResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaskSetupResponse_

typedef ::cw1_world_spawner::TaskSetupResponse_<std::allocator<void> > TaskSetupResponse;

typedef boost::shared_ptr< ::cw1_world_spawner::TaskSetupResponse > TaskSetupResponsePtr;
typedef boost::shared_ptr< ::cw1_world_spawner::TaskSetupResponse const> TaskSetupResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace cw1_world_spawner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cw1_world_spawner/TaskSetupResponse";
  }

  static const char* value(const ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
;
  }

  static const char* value(const ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskSetupResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cw1_world_spawner::TaskSetupResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CW1_WORLD_SPAWNER_MESSAGE_TASKSETUPRESPONSE_H
