// Generated by gencpp from file cw1_world_spawner/Task1Service.msg
// DO NOT EDIT!


#ifndef CW1_WORLD_SPAWNER_MESSAGE_TASK1SERVICE_H
#define CW1_WORLD_SPAWNER_MESSAGE_TASK1SERVICE_H

#include <ros/service_traits.h>


#include <cw1_world_spawner/Task1ServiceRequest.h>
#include <cw1_world_spawner/Task1ServiceResponse.h>


namespace cw1_world_spawner
{

struct Task1Service
{

typedef Task1ServiceRequest Request;
typedef Task1ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Task1Service
} // namespace cw1_world_spawner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw1_world_spawner::Task1Service > {
  static const char* value()
  {
    return "f2ce7f945836acb742f2f7bc16c06e3c";
  }

  static const char* value(const ::cw1_world_spawner::Task1Service&) { return value(); }
};

template<>
struct DataType< ::cw1_world_spawner::Task1Service > {
  static const char* value()
  {
    return "cw1_world_spawner/Task1Service";
  }

  static const char* value(const ::cw1_world_spawner::Task1Service&) { return value(); }
};


// service_traits::MD5Sum< ::cw1_world_spawner::Task1ServiceRequest> should match
// service_traits::MD5Sum< ::cw1_world_spawner::Task1Service >
template<>
struct MD5Sum< ::cw1_world_spawner::Task1ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw1_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw1_world_spawner::Task1ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1_world_spawner::Task1ServiceRequest> should match
// service_traits::DataType< ::cw1_world_spawner::Task1Service >
template<>
struct DataType< ::cw1_world_spawner::Task1ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::cw1_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw1_world_spawner::Task1ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw1_world_spawner::Task1ServiceResponse> should match
// service_traits::MD5Sum< ::cw1_world_spawner::Task1Service >
template<>
struct MD5Sum< ::cw1_world_spawner::Task1ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw1_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw1_world_spawner::Task1ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1_world_spawner::Task1ServiceResponse> should match
// service_traits::DataType< ::cw1_world_spawner::Task1Service >
template<>
struct DataType< ::cw1_world_spawner::Task1ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::cw1_world_spawner::Task1Service >::value();
  }
  static const char* value(const ::cw1_world_spawner::Task1ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW1_WORLD_SPAWNER_MESSAGE_TASK1SERVICE_H
