// Generated by gencpp from file cw1_team_10/example.msg
// DO NOT EDIT!


#ifndef CW1_TEAM_10_MESSAGE_EXAMPLE_H
#define CW1_TEAM_10_MESSAGE_EXAMPLE_H

#include <ros/service_traits.h>


#include <cw1_team_10/exampleRequest.h>
#include <cw1_team_10/exampleResponse.h>


namespace cw1_team_10
{

struct example
{

typedef exampleRequest Request;
typedef exampleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct example
} // namespace cw1_team_10


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cw1_team_10::example > {
  static const char* value()
  {
    return "978efc3b4d217b6a9fca06d03983e5b2";
  }

  static const char* value(const ::cw1_team_10::example&) { return value(); }
};

template<>
struct DataType< ::cw1_team_10::example > {
  static const char* value()
  {
    return "cw1_team_10/example";
  }

  static const char* value(const ::cw1_team_10::example&) { return value(); }
};


// service_traits::MD5Sum< ::cw1_team_10::exampleRequest> should match
// service_traits::MD5Sum< ::cw1_team_10::example >
template<>
struct MD5Sum< ::cw1_team_10::exampleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cw1_team_10::example >::value();
  }
  static const char* value(const ::cw1_team_10::exampleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1_team_10::exampleRequest> should match
// service_traits::DataType< ::cw1_team_10::example >
template<>
struct DataType< ::cw1_team_10::exampleRequest>
{
  static const char* value()
  {
    return DataType< ::cw1_team_10::example >::value();
  }
  static const char* value(const ::cw1_team_10::exampleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cw1_team_10::exampleResponse> should match
// service_traits::MD5Sum< ::cw1_team_10::example >
template<>
struct MD5Sum< ::cw1_team_10::exampleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cw1_team_10::example >::value();
  }
  static const char* value(const ::cw1_team_10::exampleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cw1_team_10::exampleResponse> should match
// service_traits::DataType< ::cw1_team_10::example >
template<>
struct DataType< ::cw1_team_10::exampleResponse>
{
  static const char* value()
  {
    return DataType< ::cw1_team_10::example >::value();
  }
  static const char* value(const ::cw1_team_10::exampleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CW1_TEAM_10_MESSAGE_EXAMPLE_H
